import type { Oportunidade } from "./types";

export const SEED: Array<Omit<Oportunidade, "origem" | "fonteId" | "fonteUrl">> = [
  {
    id: "pibic-cnpq-2026",
    titulo: "PIBIC — Bolsa de Iniciação Científica CNPq",
    tipo: "bolsa",
    organizacao: "CNPq",
    descricao:
      "Programa Institucional de Bolsas de Iniciação Científica para estudantes de graduação desenvolverem pesquisa com orientação de um pesquisador. A inscrição é feita pela pró-reitoria de pesquisa da sua universidade, que publica o edital interno.",
    area: "Multidisciplinar",
    nivel: "graduacao",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: null,
    beneficio: "R$ 700/mês",
    prazoInscricao: "2026-09-30",
    dataInicio: "2027-03-01",
    dataFim: "2028-02-29",
    urlInscricao: "https://www.gov.br/cnpq/pt-br",
    requisitos: [
      "Estar matriculado em graduação",
      "Não ter vínculo empregatício",
      "Ter um orientador credenciado",
    ],
    tags: ["iniciação científica", "pesquisa", "graduação"],
    vagas: null,
    criadoEm: "2026-06-01T12:00:00.000Z",
    atualizadoEm: "2026-06-01T12:00:00.000Z",
  },
  {
    id: "capes-ds-mestrado",
    titulo: "Bolsa CAPES Demanda Social — Mestrado",
    tipo: "bolsa",
    organizacao: "CAPES",
    descricao:
      "Bolsa de mestrado acadêmico para programas de pós-graduação stricto sensu recomendados pela CAPES. A seleção é feita pelo próprio programa de pós-graduação, que distribui as cotas recebidas.",
    area: "Multidisciplinar",
    nivel: "pos-graduacao",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: null,
    beneficio: "R$ 2.100/mês",
    prazoInscricao: "2026-10-15",
    dataInicio: "2027-03-01",
    dataFim: null,
    urlInscricao: "https://www.gov.br/capes/pt-br",
    requisitos: [
      "Ser aprovado em programa de mestrado recomendado pela CAPES",
      "Dedicação exclusiva, salvo exceções do programa",
    ],
    tags: ["mestrado", "pós-graduação", "CAPES"],
    vagas: null,
    criadoEm: "2026-05-12T12:00:00.000Z",
    atualizadoEm: "2026-05-12T12:00:00.000Z",
  },
  {
    id: "fapesp-ic",
    titulo: "Bolsa FAPESP de Iniciação Científica",
    tipo: "bolsa",
    organizacao: "FAPESP",
    descricao:
      "Bolsa para alunos de graduação em instituições do Estado de São Paulo. O pedido é apresentado pelo pesquisador responsável e avaliado em fluxo contínuo, com início previsto cerca de 75 dias após a submissão.",
    area: "Multidisciplinar",
    nivel: "graduacao",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: "São Paulo",
    beneficio: "R$ 1.220,10/mês",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://fapesp.br/bolsas/ic",
    requisitos: [
      "Estar matriculado em instituição de SP",
      "Ter um pesquisador responsável elegível na FAPESP",
      "Dedicar 12 a 20 horas semanais ao projeto",
    ],
    tags: ["FAPESP", "São Paulo", "pesquisa"],
    vagas: null,
    criadoEm: "2026-04-02T12:00:00.000Z",
    atualizadoEm: "2026-04-02T12:00:00.000Z",
  },
  {
    id: "fundacao-estudar",
    titulo: "Programa de Bolsas Fundação Estudar",
    tipo: "bolsa",
    organizacao: "Fundação Estudar",
    descricao:
      "Bolsa de estudos e formação de lideranças para universitários de alta performance. Além do apoio financeiro, o programa oferece mentoria, rede de alumni e oficinas de carreira.",
    area: "Multidisciplinar",
    nivel: "graduacao",
    modalidade: "hibrido",
    pais: "Brasil",
    cidade: null,
    beneficio: "Até 100% da mensalidade + formação",
    prazoInscricao: "2026-08-28",
    dataInicio: "2027-02-01",
    dataFim: null,
    urlInscricao: "https://www.estudar.org.br",
    requisitos: [
      "Estar cursando ou ingressar na graduação",
      "Histórico acadêmico sólido",
      "Ensaios e entrevistas de seleção",
    ],
    tags: ["liderança", "graduação", "mentoria"],
    vagas: 80,
    criadoEm: "2026-07-01T12:00:00.000Z",
    atualizadoEm: "2026-07-01T12:00:00.000Z",
  },
  {
    id: "chevening-2027",
    titulo: "Chevening Scholarship — Mestrado no Reino Unido",
    tipo: "bolsa",
    organizacao: "UK Foreign, Commonwealth & Development Office",
    descricao:
      "Bolsa integral para mestrado de um ano em universidades do Reino Unido. Cobre mensalidade, passagem, visto e custo de vida. Exige plano de retorno ao país de origem e potencial de liderança.",
    area: "Multidisciplinar",
    nivel: "pos-graduacao",
    modalidade: "presencial",
    pais: "Reino Unido",
    cidade: null,
    beneficio: "Mensalidade + custo de vida + passagem",
    prazoInscricao: "2026-11-05",
    dataInicio: "2027-09-01",
    dataFim: "2028-09-01",
    urlInscricao: "https://www.chevening.org/apply/",
    requisitos: [
      "Graduação concluída",
      "Pelo menos dois anos de experiência profissional",
      "Inglês no nível exigido pela universidade",
    ],
    tags: ["Reino Unido", "mestrado", "internacional"],
    vagas: null,
    criadoEm: "2026-07-20T12:00:00.000Z",
    atualizadoEm: "2026-07-20T12:00:00.000Z",
  },
  {
    id: "fulbright-mestrado",
    titulo: "Fulbright — Mestrado e Doutorado nos EUA",
    tipo: "bolsa",
    organizacao: "Comissão Fulbright Brasil",
    descricao:
      "Bolsas para pós-graduação em universidades americanas, com cobertura de mensalidade, seguro, auxílio-moradia e passagem. O processo inclui proposta acadêmica, cartas de recomendação e entrevista.",
    area: "Multidisciplinar",
    nivel: "pos-graduacao",
    modalidade: "presencial",
    pais: "Estados Unidos",
    cidade: null,
    beneficio: "Mensalidade + stipend + passagem",
    prazoInscricao: "2026-09-15",
    dataInicio: "2027-08-01",
    dataFim: null,
    urlInscricao: "https://fulbright.org.br",
    requisitos: [
      "Nacionalidade brasileira",
      "Excelência acadêmica",
      "TOEFL ou equivalente",
    ],
    tags: ["EUA", "Fulbright", "pós-graduação"],
    vagas: null,
    criadoEm: "2026-05-30T12:00:00.000Z",
    atualizadoEm: "2026-05-30T12:00:00.000Z",
  },
  {
    id: "erasmus-mundus",
    titulo: "Erasmus Mundus Joint Masters",
    tipo: "bolsa",
    organizacao: "Comissão Europeia",
    descricao:
      "Mestrados conjuntos em pelo menos dois países europeus, com bolsa que cobre mensalidade, viagem e subsistência. Cada consórcio tem edital próprio: escolha o curso no catálogo e candidate-se direto ao programa.",
    area: "Multidisciplinar",
    nivel: "pos-graduacao",
    modalidade: "presencial",
    pais: "União Europeia",
    cidade: null,
    beneficio: "Até € 1.400/mês + mensalidade",
    prazoInscricao: "2027-01-15",
    dataInicio: "2027-09-01",
    dataFim: "2029-08-31",
    urlInscricao:
      "https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en",
    requisitos: [
      "Graduação concluída ou a concluir até o início do curso",
      "Inglês e, em alguns programas, outro idioma europeu",
    ],
    tags: ["Europa", "mestrado", "mobilidade"],
    vagas: null,
    criadoEm: "2026-06-18T12:00:00.000Z",
    atualizadoEm: "2026-06-18T12:00:00.000Z",
  },
  {
    id: "daad-alemanha",
    titulo: "DAAD Study Scholarships — Alemanha",
    tipo: "bolsa",
    organizacao: "DAAD",
    descricao:
      "Bolsas para mestrado e pesquisa na Alemanha em todas as áreas. O DAAD oferece várias linhas; a mais procurada cobre 10 a 24 meses de estudo com seguro-saúde e auxílio-deslocamento.",
    area: "Multidisciplinar",
    nivel: "pos-graduacao",
    modalidade: "presencial",
    pais: "Alemanha",
    cidade: null,
    beneficio: "€ 992/mês + seguro",
    prazoInscricao: "2026-10-31",
    dataInicio: "2027-10-01",
    dataFim: null,
    urlInscricao: "https://www.daad.de/en/studying-in-germany/scholarships/",
    requisitos: [
      "Graduação concluída",
      "Carta de aceitação ou contato com universidade alemã",
      "Alemão ou inglês, conforme o curso",
    ],
    tags: ["Alemanha", "DAAD", "mestrado"],
    vagas: null,
    criadoEm: "2026-04-22T12:00:00.000Z",
    atualizadoEm: "2026-04-22T12:00:00.000Z",
  },
  {
    id: "santander-open-academy",
    titulo: "Santander Open Academy — Bolsas de cursos",
    tipo: "bolsa",
    organizacao: "Santander Universidades",
    descricao:
      "Bolsas para cursos curtos de habilidades digitais, idiomas e carreira em parceiros como Cambridge, MIT e Google. Novas turmas abrem ao longo do ano; a inscrição é 100% online.",
    area: "Negócios",
    nivel: "todos",
    modalidade: "remoto",
    pais: "Internacional",
    cidade: null,
    beneficio: "Curso gratuito (valor de mercado até R$ 5.000)",
    prazoInscricao: "2026-09-08",
    dataInicio: "2026-10-01",
    dataFim: "2026-12-15",
    urlInscricao: "https://www.santanderopenacademy.com/pt/index.html",
    requisitos: [
      "Ter 18 anos ou mais",
      "Cadastro na plataforma Santander Open Academy",
    ],
    tags: ["cursos", "carreira", "remoto"],
    vagas: 5000,
    criadoEm: "2026-08-01T12:00:00.000Z",
    atualizadoEm: "2026-08-01T12:00:00.000Z",
  },
  {
    id: "campus-party-brasil",
    titulo: "Campus Party Brasil",
    tipo: "evento",
    organizacao: "Campus Party",
    descricao:
      "Festival de tecnologia, ciência e inovação com palestras, hackathons, arenas de games e networking. Há passes para campuseiros (com acampamento) e ingressos diários.",
    area: "Ciência da Computação",
    nivel: "todos",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: "São Paulo",
    beneficio: "Ingressos a partir de R$ 180",
    prazoInscricao: "2026-10-20",
    dataInicio: "2026-11-11",
    dataFim: "2026-11-15",
    urlInscricao: "https://campusparty.com.br",
    requisitos: ["Ingresso válido", "Documento com foto"],
    tags: ["tecnologia", "hackathon", "networking"],
    vagas: null,
    criadoEm: "2026-07-10T12:00:00.000Z",
    atualizadoEm: "2026-07-10T12:00:00.000Z",
  },
  {
    id: "python-brasil-2026",
    titulo: "Python Brasil 2026",
    tipo: "evento",
    organizacao: "Associação Python Brasil",
    descricao:
      "Principal conferência da comunidade Python no país: tutoriais, palestras técnicas, sprints de código aberto e encontro de grupos de usuários. Oferece bolsas de diversidade para quem não pode pagar o ingresso.",
    area: "Ciência da Computação",
    nivel: "todos",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: "Florianópolis",
    beneficio: "Bolsas de diversidade disponíveis",
    prazoInscricao: "2026-09-22",
    dataInicio: "2026-10-21",
    dataFim: "2026-10-27",
    urlInscricao: "https://pythonbrasil.org.br",
    requisitos: ["Inscrição no site do evento"],
    tags: ["Python", "open source", "comunidade"],
    vagas: null,
    criadoEm: "2026-06-08T12:00:00.000Z",
    atualizadoEm: "2026-06-08T12:00:00.000Z",
  },
  {
    id: "tdc-sao-paulo",
    titulo: "The Developer's Conference — São Paulo",
    tipo: "evento",
    organizacao: "The Developer's Conference",
    descricao:
      "Conferência com trilhas paralelas de backend, dados, IA, produto e gestão. Boa para quem busca conteúdo aplicado e contato com empresas que contratam no local.",
    area: "Ciência da Computação",
    nivel: "todos",
    modalidade: "hibrido",
    pais: "Brasil",
    cidade: "São Paulo",
    beneficio: "Trilhas presenciais e online",
    prazoInscricao: "2026-08-25",
    dataInicio: "2026-09-02",
    dataFim: "2026-09-06",
    urlInscricao: "https://thedevconf.com",
    requisitos: ["Ingresso por trilha"],
    tags: ["desenvolvimento", "IA", "carreira"],
    vagas: null,
    criadoEm: "2026-07-15T12:00:00.000Z",
    atualizadoEm: "2026-07-15T12:00:00.000Z",
  },
  {
    id: "csbc-2026",
    titulo: "CSBC — Congresso da Sociedade Brasileira de Computação",
    tipo: "evento",
    organizacao: "SBC",
    descricao:
      "Maior congresso acadêmico de computação do Brasil, com eventos satélites como o CTD, WEI e WIT. Aceita artigos, pôsteres e participação como ouvinte. Ideal para quem pensa em pós-graduação.",
    area: "Ciência da Computação",
    nivel: "graduacao",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: "Porto Alegre",
    beneficio: "Inscrição reduzida para sócios SBC",
    prazoInscricao: "2026-12-01",
    dataInicio: "2027-07-20",
    dataFim: "2027-07-24",
    urlInscricao: "https://csbc.sbc.org.br",
    requisitos: ["Artigo aceito ou inscrição de ouvinte"],
    tags: ["pesquisa", "SBC", "computação"],
    vagas: null,
    criadoEm: "2026-03-11T12:00:00.000Z",
    atualizadoEm: "2026-03-11T12:00:00.000Z",
  },
  {
    id: "space-apps-2026",
    titulo: "NASA International Space Apps Challenge",
    tipo: "evento",
    organizacao: "NASA",
    descricao:
      "Hackathon mundial de 48 horas com dados abertos da NASA. Equipes criam soluções para desafios de clima, espaço e Terra. Há edições presenciais em várias cidades brasileiras e participação remota.",
    area: "Ciência da Computação",
    nivel: "todos",
    modalidade: "hibrido",
    pais: "Internacional",
    cidade: null,
    beneficio: "Gratuito · finalistas globais",
    prazoInscricao: "2026-09-30",
    dataInicio: "2026-10-03",
    dataFim: "2026-10-05",
    urlInscricao: "https://www.spaceappschallenge.org",
    requisitos: ["Equipe de 2 a 6 pessoas", "Cadastro na plataforma oficial"],
    tags: ["hackathon", "NASA", "dados abertos"],
    vagas: null,
    criadoEm: "2026-08-05T12:00:00.000Z",
    atualizadoEm: "2026-08-05T12:00:00.000Z",
  },
  {
    id: "nubank-estagio",
    titulo: "Estágio em Engenharia — Nubank",
    tipo: "estagio",
    organizacao: "Nubank",
    descricao:
      "Programa de estágio para quem está na graduação e quer trabalhar com produtos financeiros em larga escala. O ciclo costuma incluir teste técnico, entrevistas e matching com times de engenharia, dados ou produto.",
    area: "Ciência da Computação",
    nivel: "graduacao",
    modalidade: "remoto",
    pais: "Brasil",
    cidade: null,
    beneficio: "Bolsa-auxílio competitiva + VR + auxílio-educação",
    prazoInscricao: "2026-09-12",
    dataInicio: "2027-01-12",
    dataFim: null,
    urlInscricao: "https://nubank.com.br/carreira/",
    requisitos: [
      "Cursando graduação com formatura prevista a partir de 2027",
      "Disponibilidade de 30h semanais",
    ],
    tags: ["fintech", "engenharia", "remoto"],
    vagas: 120,
    criadoEm: "2026-08-10T12:00:00.000Z",
    atualizadoEm: "2026-08-10T12:00:00.000Z",
  },
  {
    id: "petrobras-estagio",
    titulo: "Programa de Estágio Petrobras",
    tipo: "estagio",
    organizacao: "Petrobras",
    descricao:
      "Estágio em engenharia, geociências, TI, jurídico e áreas corporativas. O processo é por edital público, com prova objetiva e análise curricular. Vagas em várias unidades do país.",
    area: "Engenharia",
    nivel: "graduacao",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: "Rio de Janeiro",
    beneficio: "Bolsa de até R$ 2.500 + auxílio-transporte",
    prazoInscricao: "2026-10-10",
    dataInicio: "2027-02-02",
    dataFim: null,
    urlInscricao: "https://www.petrobras.com.br",
    requisitos: [
      "Estar matriculado em curso superior compatível",
      "Previsão de formatura compatível com o edital",
    ],
    tags: ["energia", "edital", "engenharia"],
    vagas: 800,
    criadoEm: "2026-07-28T12:00:00.000Z",
    atualizadoEm: "2026-07-28T12:00:00.000Z",
  },
  {
    id: "brafitec",
    titulo: "BRAFITEC — Intercâmbio Brasil–França em Engenharia",
    tipo: "intercambio",
    organizacao: "CAPES / Embaixada da França",
    descricao:
      "Mobilidade de um a dois semestres em escolas de engenharia francesas, com bolsa de manutenção. A candidatura passa pela coordenação do convênio na sua universidade.",
    area: "Engenharia",
    nivel: "graduacao",
    modalidade: "presencial",
    pais: "França",
    cidade: null,
    beneficio: "Bolsa de manutenção + isenção de mensalidade",
    prazoInscricao: "2026-11-20",
    dataInicio: "2027-09-01",
    dataFim: "2028-02-28",
    urlInscricao: "https://www.gov.br/capes/pt-br",
    requisitos: [
      "Estar em universidade com convênio BRAFITEC",
      "Bom rendimento acadêmico",
      "Francês ou inglês, conforme a escola de destino",
    ],
    tags: ["França", "engenharia", "mobilidade"],
    vagas: null,
    criadoEm: "2026-05-04T12:00:00.000Z",
    atualizadoEm: "2026-05-04T12:00:00.000Z",
  },
  {
    id: "santander-ies",
    titulo: "Bolsas Santander Ibero-Americanas",
    tipo: "intercambio",
    organizacao: "Santander Universidades",
    descricao:
      "Auxílio financeiro para um semestre em universidades da América Latina, Espanha ou Portugal parceiras da sua instituição. A seleção é feita internamente pela universidade de origem.",
    area: "Multidisciplinar",
    nivel: "graduacao",
    modalidade: "presencial",
    pais: "Portugal",
    cidade: null,
    beneficio: "€ 3.000 de auxílio",
    prazoInscricao: "2026-12-15",
    dataInicio: "2027-08-15",
    dataFim: "2028-01-31",
    urlInscricao: "https://www.becas-santander.com",
    requisitos: [
      "Estar matriculado em universidade parceira",
      "Carta de aceite da universidade de destino",
    ],
    tags: ["intercâmbio", "Ibero-América", "Santander"],
    vagas: 1000,
    criadoEm: "2026-06-25T12:00:00.000Z",
    atualizadoEm: "2026-06-25T12:00:00.000Z",
  },
  {
    id: "obi-2027",
    titulo: "Olimpíada Brasileira de Informática",
    tipo: "concurso",
    organizacao: "SBC / UNICAMP",
    descricao:
      "Competição de programação para alunos do ensino fundamental, médio e técnico. A primeira fase é na escola; medalhistas da seletiva classificam para a fase nacional e, no nível avançado, para a IOI.",
    area: "Ciência da Computação",
    nivel: "ensino-medio",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: null,
    beneficio: "Medalhas, menções e convite à seletiva da IOI",
    prazoInscricao: "2027-03-10",
    dataInicio: "2027-04-15",
    dataFim: "2027-08-20",
    urlInscricao: "https://olimpiada.ic.unicamp.br",
    requisitos: [
      "Estar matriculado no ensino fundamental, médio ou técnico",
      "Escola inscrita pela coordenação local",
    ],
    tags: ["olimpíada", "programação", "ensino médio"],
    vagas: null,
    criadoEm: "2026-08-12T12:00:00.000Z",
    atualizadoEm: "2026-08-12T12:00:00.000Z",
  },
  {
    id: "google-certificates",
    titulo: "Google Career Certificates — bolsas Coursera",
    tipo: "curso",
    organizacao: "Google / Coursera",
    descricao:
      "Certificados profissionais em análise de dados, UX, suporte de TI, cibersegurança e gestão de projetos. Há bolsas que zeram a mensalidade do Coursera por seis meses para quem demonstra necessidade.",
    area: "Ciência da Computação",
    nivel: "todos",
    modalidade: "remoto",
    pais: "Internacional",
    cidade: null,
    beneficio: "Gratuito com bolsa (senão ~US$ 49/mês)",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://grow.google/certificates/",
    requisitos: [
      "Conta no Coursera",
      "Para a bolsa: formulário de necessidade financeira",
    ],
    tags: ["certificado", "carreira", "remoto"],
    vagas: null,
    criadoEm: "2026-02-14T12:00:00.000Z",
    atualizadoEm: "2026-02-14T12:00:00.000Z",
  },
  {
    id: "fiocruz-verao",
    titulo: "Curso de Verão Fiocruz — Saúde Pública",
    tipo: "curso",
    organizacao: "Fiocruz",
    descricao:
      "Disciplinas intensivas de epidemiologia, bioestatística e saúde coletiva para graduandos e recém-formados. Algumas turmas oferecem isenção de taxa e auxílio para participantes de fora do Rio.",
    area: "Saúde",
    nivel: "graduacao",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: "Rio de Janeiro",
    beneficio: "Isenção de taxa + auxílio para selecionados",
    prazoInscricao: "2026-11-30",
    dataInicio: "2027-01-12",
    dataFim: "2027-02-06",
    urlInscricao: "https://www.fiocruz.br",
    requisitos: [
      "Cursando ou formado em área da saúde ou afins",
      "Carta de motivação",
    ],
    tags: ["saúde pública", "verão", "Fiocruz"],
    vagas: 200,
    criadoEm: "2026-07-02T12:00:00.000Z",
    atualizadoEm: "2026-07-02T12:00:00.000Z",
  },
  {
    id: "capes-print-encerrado",
    titulo: "CAPES PrInt — Doutorado Sanduíche (edital 2025)",
    tipo: "bolsa",
    organizacao: "CAPES",
    descricao:
      "Edital anterior de doutorado sanduíche no exterior pelo Programa Institucional de Internacionalização. Mantido no catálogo como referência histórica: as inscrições deste ciclo já se encerraram.",
    area: "Multidisciplinar",
    nivel: "pos-graduacao",
    modalidade: "presencial",
    pais: "Internacional",
    cidade: null,
    beneficio: "Mensalidade no exterior + passagem + seguro",
    prazoInscricao: "2026-04-30",
    dataInicio: "2026-09-01",
    dataFim: "2027-08-31",
    urlInscricao: "https://www.gov.br/capes/pt-br",
    requisitos: [
      "Estar matriculado em doutorado de IES participante do PrInt",
      "Projeto aprovado pelo programa",
    ],
    tags: ["doutorado", "sanduíche", "internacional"],
    vagas: null,
    criadoEm: "2025-11-01T12:00:00.000Z",
    atualizadoEm: "2026-05-01T12:00:00.000Z",
  },
];
