import type { Oportunidade } from "./types";

export const SEED: Array<Omit<Oportunidade, "origem" | "fonteId" | "fonteUrl" | "subtitulo">> = [
  {
    id: "pibic-cnpq-2026",
    titulo: "PIBIC — Bolsa de Iniciação Científica CNPq",
    tipo: "bolsa",
    organizacao: "CNPq",
    descricao:
      "Programa Institucional de Bolsas de Iniciação Científica para estudantes de graduação desenvolverem pesquisa com orientação de um pesquisador. A inscrição é feita pela pró-reitoria de pesquisa da sua universidade, que publica o edital interno.",
    area: "Multidisciplinar",
    nivel: "graduacao",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: null,
    beneficio: "R$ 700/mês",
    prazoInscricao: "2026-09-30",
    dataInicio: "2027-03-01",
    dataFim: "2028-02-29",
    urlInscricao: "https://www.gov.br/cnpq/pt-br",
    requisitos: [
      "Estar matriculado em graduação",
      "Não ter vínculo empregatício",
      "Ter um orientador credenciado",
    ],
    tags: ["Iniciação científica", "Pesquisa", "Graduação"],
    vagas: null,
    criadoEm: "2026-06-01T12:00:00.000Z",
    atualizadoEm: "2026-06-01T12:00:00.000Z",
  },
  {
    id: "capes-ds-mestrado",
    titulo: "Bolsa CAPES Demanda Social — Mestrado",
    tipo: "bolsa",
    organizacao: "CAPES",
    descricao:
      "Bolsa de mestrado acadêmico para programas de pós-graduação stricto sensu recomendados pela CAPES. A seleção é feita pelo próprio programa de pós-graduação, que distribui as cotas recebidas.",
    area: "Multidisciplinar",
    nivel: "pos-graduacao",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: null,
    beneficio: "R$ 2.100/mês",
    prazoInscricao: "2026-10-15",
    dataInicio: "2027-03-01",
    dataFim: null,
    urlInscricao: "https://www.gov.br/capes/pt-br",
    requisitos: [
      "Ser aprovado em programa de mestrado recomendado pela CAPES",
      "Dedicação exclusiva, salvo exceções do programa",
    ],
    tags: ["Mestrado", "Pós-graduação", "CAPES"],
    vagas: null,
    criadoEm: "2026-05-12T12:00:00.000Z",
    atualizadoEm: "2026-05-12T12:00:00.000Z",
  },
  {
    id: "fapesp-ic",
    titulo: "Bolsa FAPESP de Iniciação Científica",
    tipo: "bolsa",
    organizacao: "FAPESP",
    descricao:
      "Bolsa para alunos de graduação em instituições do Estado de São Paulo. O pedido é apresentado pelo pesquisador responsável e avaliado em fluxo contínuo, com início previsto cerca de 75 dias após a submissão.",
    area: "Multidisciplinar",
    nivel: "graduacao",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: "São Paulo",
    beneficio: "R$ 1.220,10/mês",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://fapesp.br/bolsas/ic",
    requisitos: [
      "Estar matriculado em instituição de SP",
      "Ter um pesquisador responsável elegível na FAPESP",
      "Dedicar 12 a 20 horas semanais ao projeto",
    ],
    tags: ["FAPESP", "São Paulo", "Pesquisa"],
    vagas: null,
    criadoEm: "2026-04-02T12:00:00.000Z",
    atualizadoEm: "2026-04-02T12:00:00.000Z",
  },
  {
    id: "fundacao-estudar",
    titulo: "Programa de Bolsas Fundação Estudar",
    tipo: "bolsa",
    organizacao: "Fundação Estudar",
    descricao:
      "Bolsa de estudos e formação de lideranças para universitários de alta performance. Além do apoio financeiro, o programa oferece mentoria, rede de alumni e oficinas de carreira.",
    area: "Multidisciplinar",
    nivel: "graduacao",
    modalidade: "hibrido",
    pais: "Brasil",
    cidade: null,
    beneficio: "Até 100% da mensalidade + formação",
    prazoInscricao: "2026-08-28",
    dataInicio: "2027-02-01",
    dataFim: null,
    urlInscricao: "https://www.estudar.org.br",
    requisitos: [
      "Estar cursando ou ingressar na graduação",
      "Histórico acadêmico sólido",
      "Ensaios e entrevistas de seleção",
    ],
    tags: ["Liderança", "Graduação", "Mentoria"],
    vagas: 80,
    criadoEm: "2026-07-01T12:00:00.000Z",
    atualizadoEm: "2026-07-01T12:00:00.000Z",
  },
  {
    id: "chevening-2027",
    titulo: "Chevening Scholarship — Mestrado no Reino Unido",
    tipo: "bolsa",
    organizacao: "UK Foreign, Commonwealth & Development Office",
    descricao:
      "Bolsa integral para mestrado de um ano em universidades do Reino Unido. Cobre mensalidade, passagem, visto e custo de vida. Exige plano de retorno ao país de origem e potencial de liderança.",
    area: "Multidisciplinar",
    nivel: "pos-graduacao",
    modalidade: "presencial",
    pais: "Reino Unido",
    cidade: null,
    beneficio: "Mensalidade + custo de vida + passagem",
    prazoInscricao: "2026-11-05",
    dataInicio: "2027-09-01",
    dataFim: "2028-09-01",
    urlInscricao: "https://www.chevening.org/apply/",
    requisitos: [
      "Graduação concluída",
      "Pelo menos dois anos de experiência profissional",
      "Inglês no nível exigido pela universidade",
    ],
    tags: ["Reino Unido", "Mestrado", "Internacional"],
    vagas: null,
    criadoEm: "2026-07-20T12:00:00.000Z",
    atualizadoEm: "2026-07-20T12:00:00.000Z",
  },
  {
    id: "fulbright-mestrado",
    titulo: "Fulbright — Mestrado e Doutorado nos EUA",
    tipo: "bolsa",
    organizacao: "Comissão Fulbright Brasil",
    descricao:
      "Bolsas para pós-graduação em universidades americanas, com cobertura de mensalidade, seguro, auxílio-moradia e passagem. O processo inclui proposta acadêmica, cartas de recomendação e entrevista.",
    area: "Multidisciplinar",
    nivel: "pos-graduacao",
    modalidade: "presencial",
    pais: "Estados Unidos",
    cidade: null,
    beneficio: "Mensalidade + stipend + passagem",
    prazoInscricao: "2026-09-15",
    dataInicio: "2027-08-01",
    dataFim: null,
    urlInscricao: "https://fulbright.org.br",
    requisitos: [
      "Nacionalidade brasileira",
      "Excelência acadêmica",
      "TOEFL ou equivalente",
    ],
    tags: ["EUA", "Fulbright", "Pós-graduação"],
    vagas: null,
    criadoEm: "2026-05-30T12:00:00.000Z",
    atualizadoEm: "2026-05-30T12:00:00.000Z",
  },
  {
    id: "erasmus-mundus",
    titulo: "Erasmus Mundus Joint Masters",
    tipo: "bolsa",
    organizacao: "Comissão Europeia",
    descricao:
      "Mestrados conjuntos em pelo menos dois países europeus, com bolsa que cobre mensalidade, viagem e subsistência. Cada consórcio tem edital próprio: escolha o curso no catálogo e candidate-se direto ao programa.",
    area: "Multidisciplinar",
    nivel: "pos-graduacao",
    modalidade: "presencial",
    pais: "União Europeia",
    cidade: null,
    beneficio: "Até € 1.400/mês + mensalidade",
    prazoInscricao: "2027-01-15",
    dataInicio: "2027-09-01",
    dataFim: "2029-08-31",
    urlInscricao:
      "https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en",
    requisitos: [
      "Graduação concluída ou a concluir até o início do curso",
      "Inglês e, em alguns programas, outro idioma europeu",
    ],
    tags: ["Europa", "Mestrado", "Mobilidade"],
    vagas: null,
    criadoEm: "2026-06-18T12:00:00.000Z",
    atualizadoEm: "2026-06-18T12:00:00.000Z",
  },
  {
    id: "daad-alemanha",
    titulo: "DAAD Study Scholarships — Alemanha",
    tipo: "bolsa",
    organizacao: "DAAD",
    descricao:
      "Bolsas para mestrado e pesquisa na Alemanha em todas as áreas. O DAAD oferece várias linhas; a mais procurada cobre 10 a 24 meses de estudo com seguro-saúde e auxílio-deslocamento.",
    area: "Multidisciplinar",
    nivel: "pos-graduacao",
    modalidade: "presencial",
    pais: "Alemanha",
    cidade: null,
    beneficio: "€ 992/mês + seguro",
    prazoInscricao: "2026-10-31",
    dataInicio: "2027-10-01",
    dataFim: null,
    urlInscricao: "https://www.daad.de/en/studying-in-germany/scholarships/",
    requisitos: [
      "Graduação concluída",
      "Carta de aceitação ou contato com universidade alemã",
      "Alemão ou inglês, conforme o curso",
    ],
    tags: ["Alemanha", "DAAD", "Mestrado"],
    vagas: null,
    criadoEm: "2026-04-22T12:00:00.000Z",
    atualizadoEm: "2026-04-22T12:00:00.000Z",
  },
  {
    id: "santander-open-academy",
    titulo: "Santander Open Academy — Bolsas de cursos",
    tipo: "bolsa",
    organizacao: "Santander Universidades",
    descricao:
      "Página de bolsas e auxílios da Santander Open Academy: editais de mobilidade, pesquisa, estágios e cursos curtos com Cambridge, MIT e Google. Novas turmas e bolsas abrem ao longo do ano; a inscrição é online.",
    area: "Negócios",
    nivel: "todos",
    modalidade: "remoto",
    pais: "Internacional",
    cidade: null,
    beneficio: "Curso gratuito (valor de mercado até R$ 5.000)",
    prazoInscricao: "2026-09-08",
    dataInicio: "2026-10-01",
    dataFim: "2026-12-15",
    urlInscricao: "https://www.santanderopenacademy.com/pt_br/sites/scholarships.html",
    requisitos: [
      "Ter 18 anos ou mais",
      "Cadastro na plataforma Santander Open Academy",
    ],
    tags: ["Cursos", "Carreira", "Remoto"],
    vagas: 5000,
    criadoEm: "2026-08-01T12:00:00.000Z",
    atualizadoEm: "2026-08-01T12:00:00.000Z",
  },
  {
    id: "campus-party-brasil",
    titulo: "Campus Party Brasil",
    tipo: "evento",
    organizacao: "Campus Party",
    descricao:
      "Festival de tecnologia, ciência e inovação com palestras, hackathons, arenas de games e networking. Há passes para campuseiros (com acampamento) e ingressos diários.",
    area: "Ciência da Computação",
    nivel: "todos",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: "São Paulo",
    beneficio: "Ingressos a partir de R$ 180",
    prazoInscricao: "2026-10-20",
    dataInicio: "2026-11-11",
    dataFim: "2026-11-15",
    urlInscricao: "https://campusparty.com.br",
    requisitos: ["Ingresso válido", "Documento com foto"],
    tags: ["Tecnologia", "Hackathon", "Networking"],
    vagas: null,
    criadoEm: "2026-07-10T12:00:00.000Z",
    atualizadoEm: "2026-07-10T12:00:00.000Z",
  },
  {
    id: "python-brasil-2026",
    titulo: "Python Brasil 2026",
    tipo: "evento",
    organizacao: "Associação Python Brasil",
    descricao:
      "Principal conferência da comunidade Python no país: tutoriais, palestras técnicas, sprints de código aberto e encontro de grupos de usuários. Oferece bolsas de diversidade para quem não pode pagar o ingresso.",
    area: "Ciência da Computação",
    nivel: "todos",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: "Florianópolis",
    beneficio: "Bolsas de diversidade disponíveis",
    prazoInscricao: "2026-09-22",
    dataInicio: "2026-10-21",
    dataFim: "2026-10-27",
    urlInscricao: "https://pythonbrasil.org.br",
    requisitos: ["Inscrição no site do evento"],
    tags: ["Python", "Open source", "Comunidade"],
    vagas: null,
    criadoEm: "2026-06-08T12:00:00.000Z",
    atualizadoEm: "2026-06-08T12:00:00.000Z",
  },
  {
    id: "tdc-sao-paulo",
    titulo: "The Developer's Conference — São Paulo",
    tipo: "evento",
    organizacao: "The Developer's Conference",
    descricao:
      "Conferência com trilhas paralelas de backend, dados, IA, produto e gestão. Boa para quem busca conteúdo aplicado e contato com empresas que contratam no local.",
    area: "Ciência da Computação",
    nivel: "todos",
    modalidade: "hibrido",
    pais: "Brasil",
    cidade: "São Paulo",
    beneficio: "Trilhas presenciais e online",
    prazoInscricao: "2026-08-25",
    dataInicio: "2026-09-02",
    dataFim: "2026-09-06",
    urlInscricao: "https://thedevconf.com",
    requisitos: ["Ingresso por trilha"],
    tags: ["Desenvolvimento", "IA", "Carreira"],
    vagas: null,
    criadoEm: "2026-07-15T12:00:00.000Z",
    atualizadoEm: "2026-07-15T12:00:00.000Z",
  },
  {
    id: "csbc-2026",
    titulo: "CSBC — Congresso da Sociedade Brasileira de Computação",
    tipo: "evento",
    organizacao: "SBC",
    descricao:
      "Maior congresso acadêmico de computação do Brasil, com eventos satélites como o CTD, WEI e WIT. Aceita artigos, pôsteres e participação como ouvinte. Ideal para quem pensa em pós-graduação.",
    area: "Ciência da Computação",
    nivel: "graduacao",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: "Porto Alegre",
    beneficio: "Inscrição reduzida para sócios SBC",
    prazoInscricao: "2026-12-01",
    dataInicio: "2027-07-20",
    dataFim: "2027-07-24",
    urlInscricao: "https://csbc.sbc.org.br",
    requisitos: ["Artigo aceito ou inscrição de ouvinte"],
    tags: ["Pesquisa", "SBC", "Computação"],
    vagas: null,
    criadoEm: "2026-03-11T12:00:00.000Z",
    atualizadoEm: "2026-03-11T12:00:00.000Z",
  },
  {
    id: "space-apps-2026",
    titulo: "NASA International Space Apps Challenge",
    tipo: "evento",
    organizacao: "NASA",
    descricao:
      "Hackathon mundial de 48 horas com dados abertos da NASA. Equipes criam soluções para desafios de clima, espaço e Terra. Há edições presenciais em várias cidades brasileiras e participação remota.",
    area: "Ciência da Computação",
    nivel: "todos",
    modalidade: "hibrido",
    pais: "Internacional",
    cidade: null,
    beneficio: "Gratuito · finalistas globais",
    prazoInscricao: "2026-09-30",
    dataInicio: "2026-10-03",
    dataFim: "2026-10-05",
    urlInscricao: "https://www.spaceappschallenge.org",
    requisitos: ["Equipe de 2 a 6 pessoas", "Cadastro na plataforma oficial"],
    tags: ["Hackathon", "NASA", "Dados abertos"],
    vagas: null,
    criadoEm: "2026-08-05T12:00:00.000Z",
    atualizadoEm: "2026-08-05T12:00:00.000Z",
  },
  {
    id: "nubank-estagio",
    titulo: "Estágio em Engenharia — Nubank",
    tipo: "estagio",
    organizacao: "Nubank",
    descricao:
      "Programa de estágio para quem está na graduação e quer trabalhar com produtos financeiros em larga escala. O ciclo costuma incluir teste técnico, entrevistas e matching com times de engenharia, dados ou produto.",
    area: "Ciência da Computação",
    nivel: "graduacao",
    modalidade: "remoto",
    pais: "Brasil",
    cidade: null,
    beneficio: "Bolsa-auxílio competitiva + VR + auxílio-educação",
    prazoInscricao: "2026-09-12",
    dataInicio: "2027-01-12",
    dataFim: null,
    urlInscricao: "https://nubank.com.br/carreira/",
    requisitos: [
      "Cursando graduação com formatura prevista a partir de 2027",
      "Disponibilidade de 30h semanais",
    ],
    tags: ["Fintech", "Engenharia", "Remoto"],
    vagas: 120,
    criadoEm: "2026-08-10T12:00:00.000Z",
    atualizadoEm: "2026-08-10T12:00:00.000Z",
  },
  {
    id: "petrobras-estagio",
    titulo: "Programa de Estágio Petrobras",
    tipo: "estagio",
    organizacao: "Petrobras",
    descricao:
      "Estágio em engenharia, geociências, TI, jurídico e áreas corporativas. O processo é por edital público, com prova objetiva e análise curricular. Vagas em várias unidades do país.",
    area: "Engenharia",
    nivel: "graduacao",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: "Rio de Janeiro",
    beneficio: "Bolsa de até R$ 2.500 + auxílio-transporte",
    prazoInscricao: "2026-10-10",
    dataInicio: "2027-02-02",
    dataFim: null,
    urlInscricao: "https://www.petrobras.com.br",
    requisitos: [
      "Estar matriculado em curso superior compatível",
      "Previsão de formatura compatível com o edital",
    ],
    tags: ["Energia", "Edital", "Engenharia"],
    vagas: 800,
    criadoEm: "2026-07-28T12:00:00.000Z",
    atualizadoEm: "2026-07-28T12:00:00.000Z",
  },
  {
    id: "brafitec",
    titulo: "BRAFITEC — Intercâmbio Brasil–França em Engenharia",
    tipo: "intercambio",
    organizacao: "CAPES / Embaixada da França",
    descricao:
      "Mobilidade de um a dois semestres em escolas de engenharia francesas, com bolsa de manutenção. A candidatura passa pela coordenação do convênio na sua universidade.",
    area: "Engenharia",
    nivel: "graduacao",
    modalidade: "presencial",
    pais: "França",
    cidade: null,
    beneficio: "Bolsa de manutenção + isenção de mensalidade",
    prazoInscricao: "2026-11-20",
    dataInicio: "2027-09-01",
    dataFim: "2028-02-28",
    urlInscricao: "https://www.gov.br/capes/pt-br",
    requisitos: [
      "Estar em universidade com convênio BRAFITEC",
      "Bom rendimento acadêmico",
      "Francês ou inglês, conforme a escola de destino",
    ],
    tags: ["França", "Engenharia", "Mobilidade"],
    vagas: null,
    criadoEm: "2026-05-04T12:00:00.000Z",
    atualizadoEm: "2026-05-04T12:00:00.000Z",
  },
  {
    id: "santander-ies",
    titulo: "Bolsas Santander Ibero-Americanas",
    tipo: "intercambio",
    organizacao: "Santander Universidades",
    descricao:
      "Auxílio financeiro para um semestre em universidades da América Latina, Espanha ou Portugal parceiras da sua instituição. A seleção é feita internamente pela universidade de origem.",
    area: "Multidisciplinar",
    nivel: "graduacao",
    modalidade: "presencial",
    pais: "Portugal",
    cidade: null,
    beneficio: "€ 3.000 de auxílio",
    prazoInscricao: "2026-12-15",
    dataInicio: "2027-08-15",
    dataFim: "2028-01-31",
    urlInscricao: "https://www.becas-santander.com",
    requisitos: [
      "Estar matriculado em universidade parceira",
      "Carta de aceite da universidade de destino",
    ],
    tags: ["Intercâmbio", "Ibero-América", "Santander"],
    vagas: 1000,
    criadoEm: "2026-06-25T12:00:00.000Z",
    atualizadoEm: "2026-06-25T12:00:00.000Z",
  },
  {
    id: "obi-2027",
    titulo: "Olimpíada Brasileira de Informática",
    tipo: "concurso",
    organizacao: "SBC / UNICAMP",
    descricao:
      "Competição de programação para alunos do ensino fundamental, médio e técnico. A primeira fase é na escola; medalhistas da seletiva classificam para a fase nacional e, no nível avançado, para a IOI.",
    area: "Ciência da Computação",
    nivel: "ensino-medio",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: null,
    beneficio: "Medalhas, menções e convite à seletiva da IOI",
    prazoInscricao: "2027-03-10",
    dataInicio: "2027-04-15",
    dataFim: "2027-08-20",
    urlInscricao: "https://olimpiada.ic.unicamp.br",
    requisitos: [
      "Estar matriculado no ensino fundamental, médio ou técnico",
      "Escola inscrita pela coordenação local",
    ],
    tags: ["Olimpíada", "Programação", "Ensino médio"],
    vagas: null,
    criadoEm: "2026-08-12T12:00:00.000Z",
    atualizadoEm: "2026-08-12T12:00:00.000Z",
  },
  {
    id: "google-certificates",
    titulo: "Google Career Certificates — bolsas Coursera",
    tipo: "curso",
    organizacao: "Google / Coursera",
    descricao:
      "Certificados profissionais em análise de dados, UX, suporte de TI, cibersegurança e gestão de projetos. Há bolsas que zeram a mensalidade do Coursera por seis meses para quem demonstra necessidade.",
    area: "Ciência da Computação",
    nivel: "todos",
    modalidade: "remoto",
    pais: "Internacional",
    cidade: null,
    beneficio: "Gratuito com bolsa (senão ~US$ 49/mês)",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://grow.google/certificates/",
    requisitos: [
      "Conta no Coursera",
      "Para a bolsa: formulário de necessidade financeira",
    ],
    tags: ["Certificado", "Carreira", "Remoto"],
    vagas: null,
    criadoEm: "2026-02-14T12:00:00.000Z",
    atualizadoEm: "2026-02-14T12:00:00.000Z",
  },
  {
    id: "fiocruz-verao",
    titulo: "Curso de Verão Fiocruz — Saúde Pública",
    tipo: "curso",
    organizacao: "Fiocruz",
    descricao:
      "Disciplinas intensivas de epidemiologia, bioestatística e saúde coletiva para graduandos e recém-formados. Algumas turmas oferecem isenção de taxa e auxílio para participantes de fora do Rio.",
    area: "Saúde",
    nivel: "graduacao",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: "Rio de Janeiro",
    beneficio: "Isenção de taxa + auxílio para selecionados",
    prazoInscricao: "2026-11-30",
    dataInicio: "2027-01-12",
    dataFim: "2027-02-06",
    urlInscricao: "https://www.fiocruz.br",
    requisitos: [
      "Cursando ou formado em área da saúde ou afins",
      "Carta de motivação",
    ],
    tags: ["Saúde pública", "Verão", "Fiocruz"],
    vagas: 200,
    criadoEm: "2026-07-02T12:00:00.000Z",
    atualizadoEm: "2026-07-02T12:00:00.000Z",
  },
  {
    id: "capes-print-encerrado",
    titulo: "CAPES PrInt — Doutorado Sanduíche (edital 2025)",
    tipo: "bolsa",
    organizacao: "CAPES",
    descricao:
      "Edital anterior de doutorado sanduíche no exterior pelo Programa Institucional de Internacionalização. Mantido no catálogo como referência histórica: as inscrições deste ciclo já se encerraram.",
    area: "Multidisciplinar",
    nivel: "pos-graduacao",
    modalidade: "presencial",
    pais: "Internacional",
    cidade: null,
    beneficio: "Mensalidade no exterior + passagem + seguro",
    prazoInscricao: "2026-04-30",
    dataInicio: "2026-09-01",
    dataFim: "2027-08-31",
    urlInscricao: "https://www.gov.br/capes/pt-br",
    requisitos: [
      "Estar matriculado em doutorado de IES participante do PrInt",
      "Projeto aprovado pelo programa",
    ],
    tags: ["Doutorado", "Sanduíche", "Internacional"],
    vagas: null,
    criadoEm: "2025-11-01T12:00:00.000Z",
    atualizadoEm: "2026-05-01T12:00:00.000Z",
  },
  {
    id: "uxconf-br-2026",
    titulo: "UXConf BR 2026 — Design para germinar e regenerar",
    tipo: "evento",
    organizacao: "UXConf BR",
    descricao:
      "Conferência brasileira de UX e design de produto. A edição 2026 propõe o tema Design para germinar e regenerar, com palestras, trilhas e encontro da comunidade.",
    area: "UX e Produto",
    nivel: "todos",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: null,
    beneficio: "Ingressos no site oficial",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://www.uxconf.com.br/",
    requisitos: ["Inscrição no site da conferência"],
    tags: ["UX", "Conferência", "Brasil"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "dexconf-2026",
    titulo: "DEXCONF 2026 — Experiências conectadas",
    tipo: "evento",
    organizacao: "Mergo Escola de Design",
    descricao:
      "Encontro da comunidade brasileira de UX, organizado pela Mergo. A edição 2026 acontece no Teatro FECAP, em São Paulo, com o tema Experiências conectadas: das pessoas ao ecossistema.",
    area: "UX e Produto",
    nivel: "todos",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: "São Paulo",
    beneficio: "Ingressos (Sympla / site Mergo)",
    prazoInscricao: "2026-08-22",
    dataInicio: "2026-08-21",
    dataFim: "2026-08-22",
    urlInscricao: "https://www.mergo.com.br/eventos/dexconf/",
    requisitos: ["Inscrição antecipada; vagas limitadas"],
    tags: ["UX", "DEXConf", "São Paulo"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "link-festival-2026",
    titulo: "Link Festival — acessibilidade digital",
    tipo: "evento",
    organizacao: "Hand Talk",
    descricao:
      "Maior festival de acessibilidade digital da América Latina, online e gratuito. Em 2026 acontece nos dias 26, 28 e 30 de outubro, com encerramento transmitido do MASP.",
    area: "UX e Produto",
    nivel: "todos",
    modalidade: "hibrido",
    pais: "Brasil",
    cidade: "São Paulo",
    beneficio: "Gratuito",
    prazoInscricao: "2026-10-26",
    dataInicio: "2026-10-26",
    dataFim: "2026-10-30",
    urlInscricao: "https://linkfestival.me/",
    requisitos: ["Inscrição gratuita no site"],
    tags: ["Acessibilidade", "Festival", "Inclusão"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "mulheres-de-produto",
    titulo: "Mulheres de Produto — comunidade e eventos",
    tipo: "evento",
    organizacao: "Mulheres de Produto",
    descricao:
      "Comunidade e agenda de encontros para mulheres que trabalham com produto, UX e tecnologia. O site concentra próximos eventos, conteúdos e a rede.",
    area: "UX e Produto",
    nivel: "todos",
    modalidade: "hibrido",
    pais: "Brasil",
    cidade: null,
    beneficio: "Varia por evento",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://www.mulheresdeproduto.com/",
    requisitos: ["Acompanhar a agenda oficial"],
    tags: ["Produto", "Comunidade", "Diversidade"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "product-camp",
    titulo: "Product Camp — evento de produto",
    tipo: "evento",
    organizacao: "Product Camp",
    descricao:
      "Um dos maiores encontros de produto da América Latina, com palestras, workshops e networking para PMs, designers e lideranças de produto.",
    area: "UX e Produto",
    nivel: "todos",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: null,
    beneficio: "Ingressos no site oficial",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://www.productcamp.com.br/",
    requisitos: ["Inscrição no site"],
    tags: ["Produto", "Product management", "Brasil"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "world-usability-day-2026",
    titulo: "World Usability Day",
    tipo: "evento",
    organizacao: "World Usability Day",
    descricao:
      "Dia mundial da usabilidade: capítulos locais promovem palestras, workshops e meetups no mesmo período. O site oficial lista eventos pelo mundo, inclusive no Brasil.",
    area: "UX e Produto",
    nivel: "todos",
    modalidade: "hibrido",
    pais: "Internacional",
    cidade: null,
    beneficio: "Muitos capítulos são gratuitos",
    prazoInscricao: "2026-11-12",
    dataInicio: "2026-11-12",
    dataFim: "2026-11-12",
    urlInscricao: "https://worldusabilityday.org/",
    requisitos: ["Inscrição no capítulo local"],
    tags: ["Usabilidade", "WUD", "Meetup"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "floripa-design-days",
    titulo: "Floripa Design Days",
    tipo: "evento",
    organizacao: "Floripa Design Days",
    descricao:
      "Festival de design em Florianópolis, com palestras, workshops e encontro da cena local de produto, UX e visual.",
    area: "UX e Produto",
    nivel: "todos",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: "Florianópolis",
    beneficio: "Ingressos no site oficial",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://www.floripadesigndays.com/",
    requisitos: ["Inscrição no site"],
    tags: ["Design", "Florianópolis", "Festival"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "ifood-camp",
    titulo: "iFood Camp",
    tipo: "evento",
    organizacao: "iFood",
    descricao:
      "Encontro do iFood com o mercado de produto, design e tecnologia. Edições online e gratuitas discutem IA, comportamento e construção de produto no Brasil. Novas turmas saem no iFood Tech Blog.",
    area: "UX e Produto",
    nivel: "todos",
    modalidade: "remoto",
    pais: "Brasil",
    cidade: null,
    beneficio: "Gratuito (edições recentes)",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://negocios.ifood.com.br/eventos/ifood-camp",
    requisitos: ["Inscrição quando a edição abrir (Sympla / iFood)"],
    tags: ["IFood", "Produto", "IA"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "nu-design-day-2026",
    titulo: "Nu Design Day",
    tipo: "evento",
    organizacao: "Nubank",
    descricao:
      "Imersão na prática de design do Nubank, com cases de product design, research e content, além de conversas sobre carreira e IA. A edição de 2026 foi em 5 de agosto, em São Paulo; a página oficial é o ponto para a próxima.",
    area: "UX e Produto",
    nivel: "todos",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: "São Paulo",
    beneficio: "Gratuito na edição 2026",
    prazoInscricao: "2026-08-05",
    dataInicio: "2026-08-05",
    dataFim: "2026-08-05",
    urlInscricao: "https://nubank.com.br/nu-design-day",
    requisitos: ["Inscrição no site; vagas limitadas"],
    tags: ["Nubank", "Design", "São Paulo"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "design-day-olx-2026",
    titulo: "Design Day OLX",
    tipo: "evento",
    organizacao: "Grupo OLX",
    descricao:
      "Evento presencial do Grupo OLX sobre o futuro das interfaces. A edição 2026 é em 26 de agosto, a partir das 17h, no escritório da Paulista, com o tema Da automação à empatia.",
    area: "UX e Produto",
    nivel: "todos",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: "São Paulo",
    beneficio: "Inscrição no site; vagas limitadas",
    prazoInscricao: "2026-08-26",
    dataInicio: "2026-08-26",
    dataFim: "2026-08-26",
    urlInscricao: "https://designday.olx.com.br/",
    requisitos: ["Inscrição em designday.olx.com.br"],
    tags: ["OLX", "Design", "IA"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "lovable-day-sp-2026",
    titulo: "Lovable Day São Paulo",
    tipo: "evento",
    organizacao: "Lovable",
    descricao:
      "Maior evento presencial da Lovable, em 16 de outubro na Community Creators, em São Paulo. Palestras e casos de vibe coding, com uma semana de workshops remotos (12 a 15 de outubro) para quem tem ingresso.",
    area: "UX e Produto",
    nivel: "todos",
    modalidade: "hibrido",
    pais: "Brasil",
    cidade: "São Paulo",
    beneficio: "Ingresso presencial + workshops remotos",
    prazoInscricao: "2026-10-16",
    dataInicio: "2026-10-12",
    dataFim: "2026-10-16",
    urlInscricao: "https://www.lovableday.com.br/",
    requisitos: ["Ingresso no site oficial"],
    tags: ["Lovable", "IA", "São Paulo"],
    vagas: 1000,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "uxfor-events-hub",
    titulo: "UXFor Events Hub",
    tipo: "evento",
    organizacao: "UXFor",
    descricao:
      "Hub de eventos da UXFor: calendário de encontros, conferências e atividades da comunidade de UX no Brasil. Ponto de partida para achar a próxima edição.",
    area: "UX e Produto",
    nivel: "todos",
    modalidade: "hibrido",
    pais: "Brasil",
    cidade: null,
    beneficio: "Varia por evento",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://eventos.uxfor.com.br/",
    requisitos: ["Consultar a agenda no hub"],
    tags: ["UXFor", "Agenda", "Comunidade"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "estudar-fora",
    titulo: "Estudar Fora — bolsas para universidades no exterior",
    tipo: "intercambio",
    organizacao: "Estudar Fora",
    descricao:
      "Portal com bolsas, processos seletivos e guias para estudar em universidades no exterior. Agrega editais de mestrado, graduação e programas de verão.",
    area: "Multidisciplinar",
    nivel: "todos",
    modalidade: "presencial",
    pais: "Internacional",
    cidade: null,
    beneficio: "Varia por edital",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://www.estudarfora.org.br/",
    requisitos: ["Consultar o edital de cada bolsa"],
    tags: ["Estudar fora", "Bolsas", "Exterior"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "partiu-intercambio",
    titulo: "Partiu Intercâmbio — estudar fora com bolsa",
    tipo: "intercambio",
    organizacao: "Partiu Intercâmbio",
    descricao:
      "Site independente com editais de intercâmbio, bolsas integrais e parciais, além de guias práticos para quem quer estudar fora.",
    area: "Multidisciplinar",
    nivel: "todos",
    modalidade: "presencial",
    pais: "Internacional",
    cidade: null,
    beneficio: "Varia por edital",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://partiuintercambio.org/",
    requisitos: ["Consultar prazos de cada programa"],
    tags: ["Intercâmbio", "Bolsas", "Guia"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "bolsa-mais-brasil",
    titulo: "Bolsa Mais Brasil — bolsas de estudo",
    tipo: "bolsa",
    organizacao: "Bolsa Mais Brasil",
    descricao:
      "Agregador de bolsas de estudo em universidades e cursos no Brasil, com filtros por instituição e desconto.",
    area: "Multidisciplinar",
    nivel: "todos",
    modalidade: "hibrido",
    pais: "Brasil",
    cidade: null,
    beneficio: "Descontos e bolsas parciais",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://www.bolsamaisbrasil.com.br/",
    requisitos: ["Cadastro no site"],
    tags: ["Bolsa", "Graduação", "Brasil"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "fundacao-lemann-bolsas",
    titulo: "Fundação Lemann — bolsas e oportunidades de liderança",
    tipo: "bolsa",
    organizacao: "Fundação Lemann",
    descricao:
      "Lista de bolsas, fellowships e programas de liderança apoiados pela Fundação Lemann, no Brasil e no exterior. A página oficial concentra os editais vigentes (fellowships, Alcance, centros de pesquisa e bolsas de Direito).",
    area: "Multidisciplinar",
    nivel: "todos",
    modalidade: "hibrido",
    pais: "Brasil",
    cidade: null,
    beneficio: "Varia por programa",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://fundacaolemann.org.br/liderancas/bolsas-e-oportunidades/",
    requisitos: ["Consultar cada edital na página da Fundação"],
    tags: ["Liderança", "Lemann", "Fellowship"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "programaria",
    titulo: "PrograMaria — cursos de tecnologia com diversidade",
    tipo: "curso",
    organizacao: "PrograMaria",
    descricao:
      "Cursos e formações em tecnologia com foco em diversidade, inclusão e justiça. Turmas pagas e iniciativas gratuitas ao longo do ano.",
    area: "Ciência da Computação",
    nivel: "todos",
    modalidade: "remoto",
    pais: "Brasil",
    cidade: null,
    beneficio: "Cursos e comunidade",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://www.programaria.org/",
    requisitos: ["Inscrição nas turmas abertas"],
    tags: ["Tecnologia", "Diversidade", "Curso"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "womakerscode",
    titulo: "WoMakersCode — bootcamps e mentorias para mulheres",
    tipo: "curso",
    organizacao: "WoMakersCode",
    descricao:
      "Bootcamps, cursos e mentorias gratuitas para mulheres que querem entrar ou crescer na tecnologia. Já impactou centenas de milhares de mulheres na América Latina.",
    area: "Ciência da Computação",
    nivel: "todos",
    modalidade: "remoto",
    pais: "Brasil",
    cidade: null,
    beneficio: "Gratuito (edições típicas)",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://womakerscode.org/",
    requisitos: ["Inscrição nos bootcamps abertos"],
    tags: ["Mulheres", "Bootcamp", "Tecnologia"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "ufsc-oportunidades-internacionais",
    titulo: "UFSC — oportunidades e eventos internacionais",
    tipo: "evento",
    organizacao: "UFSC",
    descricao:
      "Agenda da Universidade Federal de Santa Catarina com congressos, schools, chamadas e mobilidade internacional. Útil também para quem não é da UFSC, como calendário de prazos.",
    area: "Multidisciplinar",
    nivel: "todos",
    modalidade: "hibrido",
    pais: "Brasil",
    cidade: "Florianópolis",
    beneficio: "Varia por edital",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://oportunidadesinternacionais.ufsc.br/category/eventos-internacionais/",
    requisitos: ["Consultar cada chamada"],
    tags: ["UFSC", "Mobilidade", "Congresso"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "carta-da-terra-jovens-lideres",
    titulo: "Programa Jovens Líderes — Carta da Terra Internacional",
    tipo: "curso",
    organizacao: "Carta da Terra Internacional",
    descricao:
      "Formação de jovens lideranças em sustentabilidade e ética do cuidado, ligada à Carta da Terra. A página do programa reúne inscrições e edições.",
    area: "Meio Ambiente",
    nivel: "todos",
    modalidade: "hibrido",
    pais: "Internacional",
    cidade: null,
    beneficio: "Formação e rede",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://cartadaterrainternacional.org/envolva-se/programa-jovens-lideres/",
    requisitos: ["Inscrição no processo seletivo vigente"],
    tags: ["Sustentabilidade", "Liderança", "Jovens"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "rio2c",
    titulo: "Rio2C — encontro de criatividade da América Latina",
    tipo: "evento",
    organizacao: "Rio2C",
    descricao:
      "Summit, conferência, mercados e Festivalia no Rio de Janeiro. Seis dias de keynotes e painéis sobre criatividade, audiovisual, música, games e inovação. A edição 2027 está marcada para 13 a 18 de abril na Cidade das Artes; as vendas de credencial abrem em breve.",
    area: "Artes e Design",
    nivel: "todos",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: "Rio de Janeiro",
    beneficio: "Credenciais Creator e Industry (vendas 2027 em breve)",
    prazoInscricao: null,
    dataInicio: "2027-04-13",
    dataFim: "2027-04-18",
    urlInscricao: "https://www.rio2c.com/",
    requisitos: ["Inscrição / credenciamento no site"],
    tags: ["Criatividade", "Rio", "Indústria criativa"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "youth-europa-go-abroad",
    titulo: "Portal Europeu da Juventude — ir para o estrangeiro",
    tipo: "intercambio",
    organizacao: "União Europeia",
    descricao:
      "Hub da Comissão Europeia com voluntariado, estudos, trabalho e intercâmbios para jovens na Europa (incluindo Erasmus+ e European Solidarity Corps).",
    area: "Multidisciplinar",
    nivel: "todos",
    modalidade: "presencial",
    pais: "União Europeia",
    cidade: null,
    beneficio: "Varia por programa (muitos com bolsa)",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://youth.europa.eu/go-abroad_pt",
    requisitos: ["Cidadania ou residência conforme cada programa"],
    tags: ["Europa", "Erasmus", "Voluntariado"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "nm-edu-ferias",
    titulo: "NM Educação — programas de férias para jovens",
    tipo: "intercambio",
    organizacao: "NM Educação Internacional",
    descricao:
      "Intercâmbios de férias no exterior com viés educacional: idiomas, academias de verão e programas para adolescentes e jovens.",
    area: "Multidisciplinar",
    nivel: "ensino-medio",
    modalidade: "presencial",
    pais: "Internacional",
    cidade: null,
    beneficio: "Programas pagos; eventuais bolsas no site",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://www.nmedu.com.br/portfolio/programas-de-ferias-para-jovens/",
    requisitos: ["Consultar idade e datas de cada destino"],
    tags: ["Férias", "Idiomas", "Jovens"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "world-creativity-day-brazil",
    titulo: "World Creativity Day Brazil",
    tipo: "evento",
    organizacao: "World Creativity Day",
    descricao:
      "Maior festival colaborativo de criatividade do mundo, na semana de 21 de abril (Dia Mundial da Criatividade e Inovação da ONU). No Brasil roda em várias cidades, em geral de 19 a 23 de abril.",
    area: "Artes e Design",
    nivel: "todos",
    modalidade: "hibrido",
    pais: "Brasil",
    cidade: null,
    beneficio: "Muitos encontros são gratuitos ou a preço popular",
    prazoInscricao: "2027-04-19",
    dataInicio: "2027-04-19",
    dataFim: "2027-04-23",
    urlInscricao: "https://worldcreativityday.com/brazil",
    requisitos: ["Inscrição no capítulo / cidade"],
    tags: ["Criatividade", "Festival", "ONU"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "world-creativity-festival",
    titulo: "World Creativity Festival",
    tipo: "evento",
    organizacao: "World Creativity Organization",
    descricao:
      "Festival mundial da criatividade ligado ao circuito do World Creativity Day. O site oficial ainda destaca a edição de 2024 em São Paulo; confira a página para a próxima cidade-sede e as datas antes de se inscrever.",
    area: "Artes e Design",
    nivel: "todos",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: "São Paulo",
    beneficio: "Programação de criatividade e inovação",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://www.worldcreativityfestival.com/",
    requisitos: ["Confirmar edição vigente no site"],
    tags: ["Festival", "Criatividade", "São Paulo"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "world-creativity-day-joinville",
    titulo: "World Creativity Day — Joinville (Região Sul)",
    tipo: "evento",
    organizacao: "World Creativity Day Joinville / ACIJ",
    descricao:
      "Polo sul do World Creativity Day em Joinville (SC). A cidade sedia o Festival Mundial da Criatividade Região Sul na semana de 19 a 23 de abril e publica a agenda em visitejoinville.com.br.",
    area: "Artes e Design",
    nivel: "todos",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: "Joinville",
    beneficio: "Atividades gratuitas na cidade",
    prazoInscricao: "2027-04-23",
    dataInicio: "2027-04-19",
    dataFim: "2027-04-23",
    urlInscricao: "https://www.visitejoinville.com.br/World-Creativity-Day",
    requisitos: ["Acompanhar a programação local"],
    tags: ["Joinville", "Criatividade", "Santa Catarina"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "hacktown-2026",
    titulo: "HackTown 2026 — 10 anos em Santa Rita do Sapucaí",
    tipo: "evento",
    organizacao: "HackTown",
    descricao:
      "Festival de tecnologia, inovação, criatividade e consciência que ocupa a cidade inteira. A 10ª edição é de 3 a 7 de setembro de 2026 em Santa Rita do Sapucaí (MG), com trilhas de IA, negócios, música e cultura. Ingressos no site e na Sympla; hospedagem some rápido.",
    area: "Ciência da Computação",
    nivel: "todos",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: "Santa Rita do Sapucaí",
    beneficio: "Ingresso de 5 dias (inteira, meia e social com doação de livro)",
    prazoInscricao: "2026-09-03",
    dataInicio: "2026-09-03",
    dataFim: "2026-09-07",
    urlInscricao: "https://hacktown.com.br/",
    requisitos: ["Ingresso válido", "Documento com foto"],
    tags: ["HackTown", "Inovação", "Minas Gerais"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "premio-brasil-criativo",
    titulo: "Prêmio Brasil Criativo",
    tipo: "concurso",
    organizacao: "Brasil Criativo",
    descricao:
      "Premiação oficial da economia criativa no Brasil, reconhecendo empreendedorismo, criatividade e inovação. Categorias e prazos saem no site a cada edição.",
    area: "Artes e Design",
    nivel: "todos",
    modalidade: "remoto",
    pais: "Brasil",
    cidade: null,
    beneficio: "Reconhecimento e vitrine",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://www.premiobrasilcriativo.com.br/",
    requisitos: ["Inscrição no regulamento da edição"],
    tags: ["Prêmio", "Economia criativa", "Concurso"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "if-design-award-2027",
    titulo: "iF Design Award 2027 — chamada para inscrições",
    tipo: "concurso",
    organizacao: "iF International Forum Design",
    descricao:
      "Um dos principais prêmios de design do mundo. A chamada 2027 aceita produtos, comunicação, arquitetura, interiores, conceitos e serviços. Inscrição no site da iF.",
    area: "Artes e Design",
    nivel: "todos",
    modalidade: "remoto",
    pais: "Internacional",
    cidade: null,
    beneficio: "Selo iF e visibilidade internacional",
    prazoInscricao: "2026-11-04",
    dataInicio: "2027-02-16",
    dataFim: "2027-04-26",
    urlInscricao: "https://ifdesign.com/en/if-design-award-2027-chamada-para-inscricoes",
    requisitos: ["Projeto inscrito nas categorias oficiais", "Taxa de inscrição conforme regulamento"],
    tags: ["IF", "Design", "Prêmio internacional"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "bda-premio-brasileiro-design-2026",
    titulo: "BDA — Prêmio Brasileiro de Design 2026",
    tipo: "concurso",
    organizacao: "BDA",
    descricao:
      "Prêmio Brasileiro de Design 2026, com o tema colaborar e transformar. Aberto a profissionais e estudantes; categorias e prazos no site oficial.",
    area: "Artes e Design",
    nivel: "todos",
    modalidade: "remoto",
    pais: "Brasil",
    cidade: null,
    beneficio: "Premiação e vitrine nacional",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://bdapremiobrasileirodesign.com.br/",
    requisitos: ["Inscrição no site do BDA"],
    tags: ["BDA", "Design brasileiro", "Prêmio"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "premio-design-abimovel",
    titulo: "Prêmio Design Abimóvel",
    tipo: "concurso",
    organizacao: "Abimóvel",
    descricao:
      "Premiação de design de mobiliário da Abimóvel, reconhecendo produtos e projetos do setor moveleiro brasileiro.",
    area: "Artes e Design",
    nivel: "todos",
    modalidade: "remoto",
    pais: "Brasil",
    cidade: null,
    beneficio: "Reconhecimento setorial",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://abimovel.com/premio-design/",
    requisitos: ["Inscrição conforme regulamento"],
    tags: ["Mobiliário", "Abimóvel", "Prêmio"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "dfbw-award",
    titulo: "DFBW Award — Design For a Better World",
    tipo: "concurso",
    organizacao: "Design For a Better World",
    descricao:
      "Prêmio de design com recorte ESG e ODS, do Centro Brasil Design, para projetos que geram impacto positivo. Inscrições da edição 2026 até 4 de setembro (R$ 520 no prazo final; há desconto para estudantes e ONGs). Cerimônia em 26 de novembro no Museu Oscar Niemeyer, em Curitiba.",
    area: "Artes e Design",
    nivel: "todos",
    modalidade: "remoto",
    pais: "Brasil",
    cidade: "Curitiba",
    beneficio: "Premiação e visibilidade de impacto",
    prazoInscricao: "2026-09-04",
    dataInicio: null,
    dataFim: "2026-11-26",
    urlInscricao: "https://dfbwaward.com/",
    requisitos: ["Projeto alinhado aos critérios ESG/ODS"],
    tags: ["Impacto", "ESG", "Design"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "premio-bornancini-2026",
    titulo: "Prêmio Bornancini de Design 2026",
    tipo: "concurso",
    organizacao: "Apdesign",
    descricao:
      "11ª edição do Prêmio Bornancini, da Apdesign, com inscrições abertas para profissionais e estudantes (produto, gráfico, embalagem, branding, UX e mais). Prazo de inscrição até 23 de setembro de 2026; cerimônia em 4 de novembro, em Porto Alegre.",
    area: "Artes e Design",
    nivel: "todos",
    modalidade: "hibrido",
    pais: "Brasil",
    cidade: "Porto Alegre",
    beneficio: "Troféu e reconhecimento",
    prazoInscricao: "2026-09-23",
    dataInicio: null,
    dataFim: "2026-11-04",
    urlInscricao: "https://premiobornancini.com.br/",
    requisitos: ["Inscrição nas categorias profissional ou estudante"],
    tags: ["Bornancini", "RS", "Design"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "dandad-awards",
    titulo: "D&AD Awards",
    tipo: "concurso",
    organizacao: "D&AD",
    descricao:
      "Premiação britânica de excelência em design e criatividade comercial (lápis de madeira, grafite, amarelo e preto). Chamada anual para agências, estúdios e estudantes.",
    area: "Artes e Design",
    nivel: "todos",
    modalidade: "remoto",
    pais: "Internacional",
    cidade: null,
    beneficio: "Lápis D&AD e prestígio internacional",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://www.dandad.org/",
    requisitos: ["Inscrição no site D&AD", "Taxa conforme categoria"],
    tags: ["D&AD", "Publicidade", "Design"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "access-plus",
    titulo: "Access+ — oportunidades educacionais para jovens",
    tipo: "bolsa",
    organizacao: "Access+",
    descricao:
      "Organização brasileira que conecta jovens a bolsas, programas de liderança e oportunidades educacionais no Brasil e no exterior.",
    area: "Multidisciplinar",
    nivel: "ensino-medio",
    modalidade: "hibrido",
    pais: "Brasil",
    cidade: null,
    beneficio: "Varia por programa",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://www.accessplus.com.br/",
    requisitos: ["Cadastro e processo seletivo de cada oportunidade"],
    tags: ["Jovens", "Bolsas", "Liderança"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "lala-latin-american-leadership-academy",
    titulo: "Latin American Leadership Academy (LALA)",
    tipo: "bolsa",
    organizacao: "Latin American Leadership Academy",
    descricao:
      "Academia de liderança para jovens da América Latina, com formação, comunidade e caminho para universidades. Processos seletivos anunciados no site.",
    area: "Negócios",
    nivel: "ensino-medio",
    modalidade: "presencial",
    pais: "Internacional",
    cidade: null,
    beneficio: "Formação e rede; bolsas conforme edital",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://latinamericanleadershipacademy.org/",
    requisitos: ["Jovem da América Latina", "Processo seletivo LALA"],
    tags: ["Liderança", "América Latina", "Ensino médio"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "rise-for-the-world",
    titulo: "Rise — programa global para jovens de 15 a 17 anos",
    tipo: "bolsa",
    organizacao: "Rise (Schmidt Futures / Rhodes Trust)",
    descricao:
      "Seleciona jovens de 15 a 17 anos com potencial de impacto social e oferece benefícios e suporte vitalícios (mentoria, comunidade, apoio a universidade e projetos).",
    area: "Multidisciplinar",
    nivel: "ensino-medio",
    modalidade: "remoto",
    pais: "Internacional",
    cidade: null,
    beneficio: "Suporte vitalício a quem é selecionado",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://www.risefortheworld.org/",
    requisitos: ["Ter entre 15 e 17 anos no ciclo vigente", "Projeto ou potencial de impacto"],
    tags: ["Rise", "Ensino médio", "Impacto social"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "engajamundo",
    titulo: "Engajamundo — jovens e impacto socioambiental",
    tipo: "curso",
    organizacao: "Engajamundo",
    descricao:
      "Organização brasileira que capacita jovens para liderar ações de impacto ambiental e social, com formações, delegações e incidência em políticas climáticas.",
    area: "Meio Ambiente",
    nivel: "todos",
    modalidade: "hibrido",
    pais: "Brasil",
    cidade: null,
    beneficio: "Formação e rede de voluntariado",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://engajamundo.org/pt/",
    requisitos: ["Inscrição nos processos e formações abertas"],
    tags: ["Clima", "Jovens", "Ativismo"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "prolider-instituto-four",
    titulo: "ProLíder — formação de lideranças (Instituto Four)",
    tipo: "curso",
    organizacao: "Instituto Four",
    descricao:
      "Programa gratuito de formação de lideranças públicas e empreendedoras. Encontros presenciais em São Paulo, trilhas de empreendedorismo e liderança pública; novas turmas abrem no site.",
    area: "Negócios",
    nivel: "todos",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: "São Paulo",
    beneficio: "Gratuito",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://www.programaprolider.com.br/",
    requisitos: ["Em geral 18 a 40 anos", "Processo seletivo com vídeo e entrevistas"],
    tags: ["Liderança", "Instituto Four", "Impacto"],
    vagas: 60,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "aiesec-brasil",
    titulo: "AIESEC — intercâmbios voluntários e profissionais",
    tipo: "intercambio",
    organizacao: "AIESEC no Brasil",
    descricao:
      "Organização global gerida por jovens. Oferece intercâmbios de voluntariado e estágios profissionais para desenvolver liderança na prática.",
    area: "Multidisciplinar",
    nivel: "graduacao",
    modalidade: "presencial",
    pais: "Internacional",
    cidade: null,
    beneficio: "Programas com taxas e, em alguns casos, bolsa/salário local",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://aiesec.org.br/",
    requisitos: ["Idade conforme o produto (em geral 18–30)", "Processo seletivo AIESEC"],
    tags: ["Voluntariado", "Liderança", "Estágio internacional"],
    vagas: null,
    criadoEm: "2026-08-22T12:00:00.000Z",
    atualizadoEm: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "fapesp-ms",
    titulo: "Bolsa FAPESP de Mestrado",
    tipo: "bolsa",
    organizacao: "FAPESP",
    descricao:
      "Bolsa para mestrado em instituições do Estado de São Paulo, em todas as áreas do conhecimento. O pedido é apresentado pelo orientador e analisado em fluxo contínuo pela FAPESP.",
    area: "Multidisciplinar",
    nivel: "pos-graduacao",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: "São Paulo",
    beneficio: "Mensalidade conforme tabela vigente da FAPESP",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://fapesp.br/bolsas/ms",
    requisitos: [
      "Matrícula em mestrado em instituição de SP",
      "Orientador elegível na FAPESP",
      "Dedicação exclusiva, salvo exceções",
    ],
    tags: ["Mestrado", "FAPESP", "Pós-graduação", "Editais abertos"],
    vagas: null,
    criadoEm: "2026-08-24T12:00:00.000Z",
    atualizadoEm: "2026-08-24T12:00:00.000Z",
  },
  {
    id: "fapesp-dr",
    titulo: "Bolsa FAPESP de Doutorado",
    tipo: "bolsa",
    organizacao: "FAPESP",
    descricao:
      "Bolsa de doutorado para pesquisa em São Paulo, aberta a todas as áreas. Submissão contínua pelo pesquisador responsável.",
    area: "Multidisciplinar",
    nivel: "pos-graduacao",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: "São Paulo",
    beneficio: "Mensalidade conforme tabela vigente da FAPESP",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://fapesp.br/bolsas/dr",
    requisitos: ["Matrícula em doutorado em instituição de SP", "Orientador elegível"],
    tags: ["Doutorado", "FAPESP", "Pós-graduação"],
    vagas: null,
    criadoEm: "2026-08-24T12:00:00.000Z",
    atualizadoEm: "2026-08-24T12:00:00.000Z",
  },
  {
    id: "prouni-mec",
    titulo: "ProUni — bolsas em universidades privadas",
    tipo: "bolsa",
    organizacao: "MEC",
    descricao:
      "Programa Universidade para Todos: bolsas integrais e parciais em cursos de graduação de instituições privadas, em todas as áreas. Inscrições nas chamadas oficiais do MEC.",
    area: "Multidisciplinar",
    nivel: "graduacao",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: null,
    beneficio: "Bolsa integral ou parcial da mensalidade",
    prazoInscricao: "2026-09-30",
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://acessounico.mec.gov.br/prouni",
    requisitos: ["Participar do ENEM conforme edital", "Critérios de renda do programa"],
    tags: ["ProUni", "MEC", "Graduação", "Editais abertos"],
    vagas: null,
    criadoEm: "2026-08-24T12:00:00.000Z",
    atualizadoEm: "2026-08-24T12:00:00.000Z",
  },
  {
    id: "fies-mec",
    titulo: "FIES — financiamento estudantil",
    tipo: "bolsa",
    organizacao: "MEC",
    descricao:
      "Fundo de Financiamento Estudantil para graduação em instituições privadas participantes, em diversas áreas. Acompanhe as aberturas no portal Acesso Único do MEC.",
    area: "Multidisciplinar",
    nivel: "graduacao",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: null,
    beneficio: "Financiamento da mensalidade conforme contrato",
    prazoInscricao: "2026-10-15",
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://acessounico.mec.gov.br/fies",
    requisitos: ["ENEM conforme edital", "Curso e instituição participantes"],
    tags: ["FIES", "MEC", "Graduação"],
    vagas: null,
    criadoEm: "2026-08-24T12:00:00.000Z",
    atualizadoEm: "2026-08-24T12:00:00.000Z",
  },
  {
    id: "fundacao-estudar",
    titulo: "Fundação Estudar — bolsas e liderança",
    tipo: "bolsa",
    organizacao: "Fundação Estudar",
    descricao:
      "Programas de bolsas e formação de lideranças para jovens de alto potencial em diversas áreas. Processos seletivos periódicos no site oficial.",
    area: "Multidisciplinar",
    nivel: "todos",
    modalidade: "hibrido",
    pais: "Brasil",
    cidade: null,
    beneficio: "Bolsa e/ou formação conforme o programa",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://www.estudar.org.br/",
    requisitos: ["Critérios do edital de cada processo"],
    tags: ["Fundação Estudar", "Jovens", "Liderança"],
    vagas: null,
    criadoEm: "2026-08-24T12:00:00.000Z",
    atualizadoEm: "2026-08-24T12:00:00.000Z",
  },
  {
    id: "obmep",
    titulo: "OBMEP — Olimpíada Brasileira de Matemática",
    tipo: "concurso",
    organizacao: "IMPA / OBMEP",
    descricao:
      "Maior olimpíada científica do Brasil para alunos do ensino fundamental e médio. Medalhistas podem concorrer a bolsas e programas de iniciação científica júnior.",
    area: "Ciências Exatas",
    nivel: "ensino-medio",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: null,
    beneficio: "Medalhas, premiações e portas para bolsas júnior",
    prazoInscricao: "2026-04-30",
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://www.obmep.org.br/",
    requisitos: ["Estar matriculado em escola brasileira participante"],
    tags: ["OBMEP", "Matemática", "Jovens", "Ensino médio"],
    vagas: null,
    criadoEm: "2026-08-24T12:00:00.000Z",
    atualizadoEm: "2026-08-24T12:00:00.000Z",
  },
  {
    id: "olimpiada-historia",
    titulo: "Olimpíada Nacional em História do Brasil",
    tipo: "concurso",
    organizacao: "Unicamp",
    descricao:
      "Olimpíada de história para estudantes do ensino fundamental e médio, com provas online e presenciais. Aberta a todas as escolas do país.",
    area: "Ciências Humanas",
    nivel: "ensino-medio",
    modalidade: "hibrido",
    pais: "Brasil",
    cidade: null,
    beneficio: "Certificados e premiações conforme edição",
    prazoInscricao: "2026-05-20",
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://www.olimpiadadehistoria.com.br/",
    requisitos: ["Matrícula em escola brasileira", "Inscrição pela escola ou conforme edital"],
    tags: ["História", "Jovens", "Ciências Humanas"],
    vagas: null,
    criadoEm: "2026-08-24T12:00:00.000Z",
    atualizadoEm: "2026-08-24T12:00:00.000Z",
  },
  {
    id: "obf-fisica",
    titulo: "OBF — Olimpíada Brasileira de Física",
    tipo: "concurso",
    organizacao: "SBF",
    descricao:
      "Olimpíada nacional de física para estudantes do ensino médio. Excelente porta de entrada para bolsas e carreiras em ciências exatas.",
    area: "Ciências Exatas",
    nivel: "ensino-medio",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: null,
    beneficio: "Medalhas e reconhecimento nacional",
    prazoInscricao: "2026-06-15",
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://www.obf.org.br/",
    requisitos: ["Estudante do ensino médio"],
    tags: ["Física", "Jovens", "Ciências Exatas"],
    vagas: null,
    criadoEm: "2026-08-24T12:00:00.000Z",
    atualizadoEm: "2026-08-24T12:00:00.000Z",
  },
  {
    id: "jovem-aprendiz-trabalho",
    titulo: "Aprendizagem profissional (Jovem Aprendiz)",
    tipo: "estagio",
    organizacao: "Ministério do Trabalho e Emprego",
    descricao:
      "Contrato de aprendizagem para jovens de 14 a 24 anos conjugando formação teórica e prática em empresas de diversos setores — não só tecnologia.",
    area: "Multidisciplinar",
    nivel: "ensino-medio",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: null,
    beneficio: "Salário proporcional + formação",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/aprendiz",
    requisitos: ["Idade conforme a lei do aprendiz", "Matrícula escolar quando exigida"],
    tags: ["Jovem aprendiz", "Jovens", "Primeiro emprego"],
    vagas: null,
    criadoEm: "2026-08-24T12:00:00.000Z",
    atualizadoEm: "2026-08-24T12:00:00.000Z",
  },
  {
    id: "gcub-mobilidade",
    titulo: "GCUB — bolsas e mobilidade acadêmica",
    tipo: "intercambio",
    organizacao: "GCUB",
    descricao:
      "Grupo Coimbra de Universidades Brasileiras: editais de bolsas e mobilidade internacional em diversas áreas do conhecimento, inclusive humanas, saúde e exatas.",
    area: "Multidisciplinar",
    nivel: "pos-graduacao",
    modalidade: "presencial",
    pais: "Internacional",
    cidade: null,
    beneficio: "Bolsa e isenção conforme edital",
    prazoInscricao: "2026-11-30",
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://www.gcub.org.br/",
    requisitos: ["Critérios do edital vigente", "Vínculo com universidade participante"],
    tags: ["GCUB", "Mestrado", "Intercâmbio", "Editais abertos"],
    vagas: null,
    criadoEm: "2026-08-24T12:00:00.000Z",
    atualizadoEm: "2026-08-24T12:00:00.000Z",
  },
  {
    id: "fiocruz-pos",
    titulo: "Fiocruz — cursos e bolsas em saúde",
    tipo: "bolsa",
    organizacao: "Fiocruz",
    descricao:
      "Editais de mestrado, doutorado e especialização em saúde coletiva, biomedicina e áreas afins. Acompanhe as chamadas no portal de ensino da Fiocruz.",
    area: "Saúde",
    nivel: "pos-graduacao",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: null,
    beneficio: "Bolsa conforme edital e agência financiadora",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://portal.fiocruz.br/",
    requisitos: ["Formação na área conforme edital"],
    tags: ["Fiocruz", "Saúde", "Mestrado", "Editais abertos"],
    vagas: null,
    criadoEm: "2026-08-24T12:00:00.000Z",
    atualizadoEm: "2026-08-24T12:00:00.000Z",
  },
  {
    id: "faperj-bolsas",
    titulo: "FAPERJ — bolsas e editais no Rio de Janeiro",
    tipo: "bolsa",
    organizacao: "FAPERJ",
    descricao:
      "Fundação de Amparo à Pesquisa do Estado do Rio de Janeiro: bolsas de IC, mestrado, doutorado e editais temáticos em todas as áreas.",
    area: "Multidisciplinar",
    nivel: "todos",
    modalidade: "presencial",
    pais: "Brasil",
    cidade: "Rio de Janeiro",
    beneficio: "Conforme edital",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://www.faperj.br/",
    requisitos: ["Vínculo com instituição do RJ", "Critérios do edital"],
    tags: ["FAPERJ", "Mestrado", "Editais abertos", "Rio de Janeiro"],
    vagas: null,
    criadoEm: "2026-08-24T12:00:00.000Z",
    atualizadoEm: "2026-08-24T12:00:00.000Z",
  },
  {
    id: "sebrae-jovens",
    titulo: "Sebrae — formação e empreendedorismo para jovens",
    tipo: "curso",
    organizacao: "Sebrae",
    descricao:
      "Cursos, mentorias e programas de empreendedorismo do Sebrae abertos a jovens e estudantes de qualquer área — negócios, serviços, agro e economia criativa.",
    area: "Negócios",
    nivel: "todos",
    modalidade: "hibrido",
    pais: "Brasil",
    cidade: null,
    beneficio: "Muitos programas gratuitos ou subsidiados",
    prazoInscricao: null,
    dataInicio: null,
    dataFim: null,
    urlInscricao: "https://sebrae.com.br/sites/PortalSebrae",
    requisitos: ["Inscrição no programa desejado"],
    tags: ["Sebrae", "Jovens", "Empreendedorismo"],
    vagas: null,
    criadoEm: "2026-08-24T12:00:00.000Z",
    atualizadoEm: "2026-08-24T12:00:00.000Z",
  },
];
